//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonTracker.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brada()
        {
            this.Skica = new HashSet<Skica>();
        }
    
        public int idBrada { get; set; }
        public byte[] Layer { get; set; }
    
        public virtual Brada Brada1 { get; set; }
        public virtual Brada Brada2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skica> Skica { get; set; }
    }
}
