//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonTracker.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komentar
    {
        public int idKomentar { get; set; }
        public string Tekst { get; set; }
        public Nullable<int> idKorisnik { get; set; }
        public Nullable<int> idNestali { get; set; }
        public Nullable<int> idPrestupnik { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Nestali Nestali { get; set; }
        public virtual Prestupnik Prestupnik { get; set; }
    }
}
