//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonTracker.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skica
    {
        public int idSkica { get; set; }
        public Nullable<int> idGlava { get; set; }
        public Nullable<int> idCeljust { get; set; }
        public Nullable<int> idObrve { get; set; }
        public Nullable<int> idOci { get; set; }
        public Nullable<int> idNos { get; set; }
        public Nullable<int> idUsne { get; set; }
        public Nullable<int> idBrada { get; set; }
        public Nullable<int> idKosa { get; set; }
        public string Foto { get; set; }
    
        public virtual Brada Brada { get; set; }
        public virtual Celjust Celjust { get; set; }
        public virtual Glava Glava { get; set; }
        public virtual Kosa Kosa { get; set; }
        public virtual Nos Nos { get; set; }
        public virtual Obrve Obrve { get; set; }
        public virtual Oci Oci { get; set; }
        public virtual Usne Usne { get; set; }
    }
}
